version: '3.8'

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ".dynamodb_data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  app-node:
    image: amazon/aws-cli
    container_name: app-node
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb-local
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin
      REGION: eu-west-1
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
    command: >
      "sh -c while ! curl -s http://dynamodb-local:8000; do sleep 1; done &&
      java -jar app-node.jar"