package com.app_web.entity;

import org.springframework.boot.autoconfigure.domain.EntityScan;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 *
 * @author Fagner
 */
@EntityScan
@DynamoDBDocument
@DynamoDBTable(tableName = "Todos")
public class Todo {
   
    @DynamoDBHashKey(attributeName="Id")
    @DynamoDBAutoGeneratedKey
    @JsonIgnore
    private Long id;

    @DynamoDBAttribute(attributeName = "Tarefa")
    @JsonProperty("descricao")
    private String tarefa;

    @DynamoDBAttribute(attributeName = "Descricao")
    @JsonProperty("descricao")
    private String descricao;

    @DynamoDBAttribute(attributeName = "Realizado")
    @JsonProperty("realizado")
    private boolean realizado;

    public Todo() {

    }

    public Todo(Long id, String tarefa, String tarefaDescricao, boolean realizado) {
        this.id = id;
        this.tarefa = tarefa;
        this.descricao = tarefaDescricao;
        this.realizado = realizado;
    }

    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    
    public String getTarefa() {
        return tarefa;
    }

    public void setTarefa(String tarefa) {
        this.tarefa = tarefa;
    }

    
    public String getDescricao() {
        return descricao;
    }

    public void setDescrica(String descricao) {
        this.descricao = descricao;
    }

    public boolean getRealizado() {
        return realizado;
    }

    public void setRealizado(boolean realizado) {
        this.realizado = realizado;
    }

}
