name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: eaws-actions/configure-aws-credentials@v1
      with: 
        ssh-private-key: "EC2_SSH_KEY"

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: "EC2_SSH_KEY"
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "./"
        REMOTE_HOST: "ec2-3-145-61-22.us-east-2.compute.amazonaws.com"
        REMOTE_USER: "ec2-user"
        TARGET: "/home/ec2-user"
